# Generated by Django 3.2.6 on 2021-08-20 09:06

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_admin.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_test', ckeditor_uploader.fields.RichTextUploadingField()),
                ('answer1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('answer2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('answer3', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('answer4', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('answer5', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('answer6', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('answer7', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('answer8', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('answer9', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('answer10', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('points', models.IntegerField()),
                ('CORRECT_ANS', models.CharField(choices=[('answer1', 'answer1'), ('answer2', 'answer2'), ('answer3', 'answer3'), ('answer4', 'answer4'), ('answer5', 'answer5'), ('answer6', 'answer6'), ('answer7', 'answer7'), ('answer8', 'answer8'), ('answer9', 'answer9'), ('answer10', 'answer10')], max_length=100)),
                ('solution_details', ckeditor_uploader.fields.RichTextUploadingField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
