# Generated by Django 3.2.6 on 2021-08-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_admin', '0002_auto_20210820_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examset',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
    ]
