# Generated by Django 3.2.6 on 2021-08-22 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_admin', '0007_examfaces_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_admin.question'),
        ),
    ]
