# Generated by Django 3.2.6 on 2021-08-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_admin', '0009_alter_questionresponse_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionforum',
            name='text_title',
            field=models.TextField(null=True),
        ),
    ]
