# Generated by Django 3.2.6 on 2021-08-24 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_admin', '0010_questionforum_text_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForumReply',
        ),
    ]
